version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 5433:5432
